# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22.12-alpine AS builder

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the project
RUN npm run build

FROM node:22.12-alpine AS installer

WORKDIR /app

# Copy package files and install only production dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts --only=production

FROM node:22.12-alpine AS release

WORKDIR /app

COPY --from=builder /app/build /app/build
COPY --from=installer /app/node_modules /app/node_modules

# Expose port if needed (Not explicitly mentioned, MCP runs via stdio, so not needed)

CMD ["node", "build/index.js"]
